language: cpp

compiler: gcc

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update

install:
    - sudo apt-get install clang-3.4
    - sudo apt-get install g++-4.8
    - sudo apt-get install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo mv libg* /usr/local/lib/
    - ls -al /usr/local/lib/libg*
    - cd -
    - sudo apt-get install libboost-all-dev
    - sudo apt-get install valgrind
    - sudo apt-get install doxygen

before_script:
    - make config
    - make versions
    - make versions CXX=clang++

script:
    - date
    - make test
    - make clean
    - make test CXX=clang++
